check if it really is that thing

diff --git a/.github/workflows/alembic-migration-test.yml b/.github/workflows/alembic-migration-test.yml
--- a/.github/workflows/alembic-migration-test.yml
+++ b/.github/workflows/alembic-migration-test.yml
@@ -64,17 +64,17 @@ jobs:
         working-directory: django-test
         run: |
           poetry install --no-root --no-ansi --dry-run
-          INSTALL_MSG=$(poetry install --no-root --no-ansi --dry-run 2>&1 | tail -1)
-          UPDATE_MSG=$(poetry update --dry-run | grep -E '([1-9]+\s(install|update|removal))+')
-          if [[ "$INSTALL_MSG" != '' || "$UPDATE_MSG" != '' ]]; then
-            echo "<h2>:no_entry_sign: Poetry check failed </h2>" >> $GITHUB_STEP_SUMMARY
-            echo "" >> $GITHUB_STEP_SUMMARY
-            echo "Install --dry-run output: " >> $GITHUB_STEP_SUMMARY
-            echo "$INSTALL_MSG" >> $GITHUB_STEP_SUMMARY
-            echo "Update --dry-run output: " >> $GITHUB_STEP_SUMMARY
-            echo "$UPDATE_MSG" >> $GITHUB_STEP_SUMMARY
-            exit 3
-          fi
+#          INSTALL_MSG=$(poetry install --no-root --no-ansi --dry-run 2>&1 | tail -1)
+#          UPDATE_MSG=$(poetry update --dry-run | grep -E '([1-9]+\s(install|update|removal))+')
+#          if [[ "$INSTALL_MSG" != '' || "$UPDATE_MSG" != '' ]]; then
+#            echo "<h2>:no_entry_sign: Poetry check failed </h2>" >> $GITHUB_STEP_SUMMARY
+#            echo "" >> $GITHUB_STEP_SUMMARY
+#            echo "Install --dry-run output: " >> $GITHUB_STEP_SUMMARY
+#            echo "$INSTALL_MSG" >> $GITHUB_STEP_SUMMARY
+#            echo "Update --dry-run output: " >> $GITHUB_STEP_SUMMARY
+#            echo "$UPDATE_MSG" >> $GITHUB_STEP_SUMMARY
+#            exit 3
+#          fi
 
       - name: fail ofzo
         if: failure()
