zo dom

diff --git a/.github/workflows/alembic-migration-test.yml b/.github/workflows/alembic-migration-test.yml
--- a/.github/workflows/alembic-migration-test.yml
+++ b/.github/workflows/alembic-migration-test.yml
@@ -81,12 +81,7 @@ jobs:
         run: |
           poetry run alembic upgrade head
           MIGRATION_MSG=$(poetry run alembic check)
-          if [[ contains("$MIGRATION_MSG", "ERROR") ]]; then
-            echo "<h2>:no_entry_sign: Migration check failed.</h2>" >> $GITHUB_STEP_SUMMARY
-            echo "<h3>The message:</h3>" >> $GITHUB_STEP_SUMMARY
-            echo "$MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
-            exit 3
-          fi
+          echo "migration_msg=$MIGRATION_MSG" >> GITHUB_OUTPUT
         env:
           CI: true
           SQL_DATABASE: ${{ vars.POSTGRES_DB }}
@@ -95,4 +90,12 @@ jobs:
           SQL_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
           SQL_PORT: 5432
 
+      - name: Output Migration Failures
+        if:  failure()
+        run: |
+          echo "<h2>:no_entry_sign: Migration check failed.</h2>" >> $GITHUB_STEP_SUMMARY
+          echo "<h3>The message:</h3>" >> $GITHUB_STEP_SUMMARY
+          echo "${{ steps.migration-check.outputs.migration_msg }}" >> $GITHUB_STEP_SUMMARY
+          exit 3
+          
         
