one-liner

diff --git a/.github/workflows/test-workflow-django.yml b/.github/workflows/test-workflow-django.yml
--- a/.github/workflows/test-workflow-django.yml
+++ b/.github/workflows/test-workflow-django.yml
@@ -78,12 +78,12 @@ jobs:
         if: true #INPUT
         run: |
           MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
-          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
-            echo "<h2>:no_entry_sign: Migration check failed </h2>
-                    <h3>The following migration(s) should be created:</h3>
-                    <br/> $MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
+#          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
+#            echo "<h2>:no_entry_sign: Migration check failed </h2>
+#                    <h3>The following migration(s) should be created:</h3>
+#                    <br/> $MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
+#            exit 1
+#          fi
 #        env:
 #          ENGINE: django.db.backends.postgresql #INPUT/SECRETS/VARS
 #          POSTGRES_DB: testdb
