zo?

diff --git a/.github/workflows/test-workflow-django.yml b/.github/workflows/test-workflow-django.yml
--- a/.github/workflows/test-workflow-django.yml
+++ b/.github/workflows/test-workflow-django.yml
@@ -79,29 +79,29 @@ jobs:
           poetry config --list
           poetry install --no-interaction --no-root --no-ansi
 
-#      - name: Download tetstmondata artifact
-#        continue-on-error: true
-#        uses: actions/download-artifact@v4
-#        with:
-#          name: django-test/.testmondata
+      #      - name: Download tetstmondata artifact
+      #        continue-on-error: true
+      #        uses: actions/download-artifact@v4
+      #        with:
+      #          name: django-test/.testmondata
 
-#      - name: Check Django Migrations
-#        working-directory: django-test #INPUT
-#        run: |
-#          MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
-#          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
-#            echo "<h2>:no_entry_sign: Migration check failed </h2>" >> $GITHUB_STEP_SUMMARY
-#            echo "<h3>The message:</h3>" >> $GITHUB_STEP_SUMMARY
-#            echo "$MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
-#            exit 3
-#          fi
-#        env:
-#          CI: true
-#          SQL_DATABASE: ${{ vars.POSTGRES_DB }}
-#          SQL_USER: ${{ vars.POSTGRES_USER }}
-#          SQL_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
-#          SQL_HOST: ${{ vars.POSTGRES_HOST }}
-#          SQL_PORT: 5432
+      #      - name: Check Django Migrations
+      #        working-directory: django-test #INPUT
+      #        run: |
+      #          MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
+      #          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
+      #            echo "<h2>:no_entry_sign: Migration check failed </h2>" >> $GITHUB_STEP_SUMMARY
+      #            echo "<h3>The message:</h3>" >> $GITHUB_STEP_SUMMARY
+      #            echo "$MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
+      #            exit 3
+      #          fi
+      #        env:
+      #          CI: true
+      #          SQL_DATABASE: ${{ vars.POSTGRES_DB }}
+      #          SQL_USER: ${{ vars.POSTGRES_USER }}
+      #          SQL_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
+      #          SQL_HOST: ${{ vars.POSTGRES_HOST }}
+      #          SQL_PORT: 5432
 
       - name: Run tests with coverage
         working-directory: django-test #INPUT
@@ -116,21 +116,21 @@ jobs:
             --testmon --durations=5 --numprocesses=2 \
             --md-report --md-report-flavor gfm --md-report-exclude-outcomes passed skipped xpassed ----md-report-output test_report.md \
             --cov-config=.coveragerc --cov-report=xml --cov=.
-#            2>&1 | tee /dev/stderr >test_report.md
           HAS_FAILURES=$(cat test_report.md | { grep 'failed' || true; } 2>&1 )
-#          echo "$HAS_FAILURES"
-#          if [ -f test_report.md ]; then
-#              if [ "$HAS_FAILURES" == '' ]; then
-#                echo "<h1>:white_check_mark: Tests Succeeded</h1>" >> $GITHUB_STEP_SUMMARY
-#              else
-#                echo "<details><summary>:x: Tests Failed</summary>" >> $GITHUB_STEP_SUMMARY
-#                echo "" >> $GITHUB_STEP_SUMMARY
-#                cat test_report.md >> $GITHUB_STEP_SUMMARY
-#                echo "" >> $GITHUB_STEP_SUMMARY
-#                echo "</details>" >> $GITHUB_STEP_SUMMARY
-#                exit 3
-#              fi
-#          fi
+        #            2>&1 | tee /dev/stderr >test_report.md
+        #          echo "$HAS_FAILURES"
+        #          if [ -f test_report.md ]; then
+        #              if [ "$HAS_FAILURES" == '' ]; then
+        #                echo "<h1>:white_check_mark: Tests Succeeded</h1>" >> $GITHUB_STEP_SUMMARY
+        #              else
+        #                echo "<details><summary>:x: Tests Failed</summary>" >> $GITHUB_STEP_SUMMARY
+        #                echo "" >> $GITHUB_STEP_SUMMARY
+        #                cat test_report.md >> $GITHUB_STEP_SUMMARY
+        #                echo "" >> $GITHUB_STEP_SUMMARY
+        #                echo "</details>" >> $GITHUB_STEP_SUMMARY
+        #                exit 3
+        #              fi
+        #          fi
         env:
           CI: true
           COLUMNS: 100
