with all pytest params

diff --git a/.github/workflows/test-workflow-django.yml b/.github/workflows/test-workflow-django.yml
--- a/.github/workflows/test-workflow-django.yml
+++ b/.github/workflows/test-workflow-django.yml
@@ -106,46 +106,44 @@ jobs:
           POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
           POSTGRES_PORT: 5432
 
-      - name: Check Django Migrations
-        working-directory: django-test #INPUT
-        run: |
-          MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
-          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
-            echo "<h2>:no_entry_sign: Migration check failed </h2>
-                    <h3>The message:</h3>
-                    <br/> $MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
-            exit 3
-          fi
-        env:
-          CI: true
-          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
-          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
-          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
-          POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
-          POSTGRES_PORT: 5432
-
-#          echo "REPORT_FILE=${REPORT_OUTPUT}" >> "$GITHUB_ENV"
-      #          pytest -v --md-report --md-report-flavor gfm --md-report-exclude-outcomes passed xpassed --md-report-output "$REPORT_OUTPUT"
-      #          if [ -f "$REPORT_FILE" ]; then
-      #            echo "<details><summary>Failed Test Report</summary>
-      #                    <br/> cat "$REPORT_FILE" <br/> </details>" >> $GITHUB_STEP_SUMMARY
-      #          fi
+#      - name: Check Django Migrations
+#        working-directory: django-test #INPUT
+#        run: |
+#          MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
+#          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
+#            echo "<h2>:no_entry_sign: Migration check failed </h2>
+#                    <h3>The message:</h3>
+#                    <br/> $MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
+#            exit 3
+#          fi
+#        env:
+#          CI: true
+#          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
+#          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
+#          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
+#          POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
+#          POSTGRES_PORT: 5432
 
       - name: Run tests with coverage
         working-directory: django-test #INPUT
-        #          MIGRATION_MSG=$(poetry run pytest --cov-config=.coveragerc --cov-report=xml --cov=. --durations=5 2>&1 )
         run: |
-          poetry run pytest --durations=5 --numprocesses=2
-          TEST_OUTPUT=$(poetry run pytest --durations=5 2>&1 )
-          HAS_FAILURES=$(echo "$TEST_OUTPUT" | grep 'failed' )
-          if [[ "$HAS_FAILURES" != '' ]]; then
-            echo "<h2>:white_check_mark: Tests Succeeded </h2>
-                    <br/> "$TEST_OUTPUT" >> $GITHUB_STEP_SUMMARY
-          else
-            echo "<h2>:x: Tests Failed </h2>
-                    <h3>The message:</h3>
-                    <br/> $TEST_OUTPUT" >> $GITHUB_STEP_SUMMARY
-            exit 3
+          poetry run pytest --cov-config=.coveragerc --cov-report=xml --cov=. --durations=5 --numprocesses=2 2>&1 | tee /dev/stderr >test_report
+          HAS_FAILURES=$(cat test_report | grep 'failed' )
+          if [ -f test_report ]; then
+              if [ "$HAS_FAILURES" == '' ]; then
+                echo "<details><summary>:white_check_mark: Tests Succeeded</summary>" >> $GITHUB_STEP_SUMMARY
+                echo "" >> $GITHUB_STEP_SUMMARY
+                cat test_report >> $GITHUB_STEP_SUMMARY
+                echo "" >> $GITHUB_STEP_SUMMARY
+                echo "</details>" >> $GITHUB_STEP_SUMMARY
+              else
+                echo "<details><summary>:x: Tests Failed</summary>" >> $GITHUB_STEP_SUMMARY
+                echo "" >> $GITHUB_STEP_SUMMARY
+                cat test_report >> $GITHUB_STEP_SUMMARY
+                echo "" >> $GITHUB_STEP_SUMMARY
+                echo "</details>" >> $GITHUB_STEP_SUMMARY
+                exit 3
+              fi
           fi
         env:
           CI: true
