reorder .env + disable steps to create cache

diff --git a/.github/workflows/test-workflow-django.yml b/.github/workflows/test-workflow-django.yml
--- a/.github/workflows/test-workflow-django.yml
+++ b/.github/workflows/test-workflow-django.yml
@@ -19,9 +19,8 @@ jobs:
         image: ${{ (true) && 'postgres' || '' }}  #INPUT
         env:
           POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: password
-          POSTGRES_DB: github_actions
-          POSTGRES_HOST: localhost
+          POSTGRES_PASSWORD: postgres
+          POSTGRES_DB: postgres
         # Set health checks to wait until postgres has started
         options: >-
           --health-cmd pg_isready
@@ -74,28 +73,29 @@ jobs:
           poetry config http-basic.repowered ${{ secrets.PRIVATE_PYPI_USER }} ${{ secrets.PRIVATE_PYPI_PASSWORD}}
           poetry install --no-interaction --no-root --no-ansi
 
-      - name: Check Django Migrations
-        working-directory: django-test #INPUT
-        if: true #INPUT
-        run: |
-          MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
-          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
-            echo "<h2>:no_entry_sign: Migration check failed </h2>
-                    <h3>The message:</h3>
-                    <br/> $MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
-        env:
-          ENGINE: django.db.backends.postgresql #INPUT/SECRETS/VARS
-          POSTGRES_DB: github_actions
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: password
-          POSTGRES_HOST: localhost
-          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
-
-      - name: Run tests with coverage
-        working-directory: django-test #INPUT
-        run: poetry run pytest --cov-config=.coveragerc --cov-report=xml --cov=. --durations=5
+#      - name: Check Django Migrations
+#        working-directory: django-test #INPUT
+#        if: true #INPUT
+#        run: |
+#          MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
+#          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
+#            echo "<h2>:no_entry_sign: Migration check failed </h2>
+#                    <h3>The message:</h3>
+#                    <br/> $MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
+#            exit 1
+#          fi
+#        env:
+#          CI: true
+#          ENGINE: django.db.backends.postgresql #INPUT/SECRETS/VARS
+#          POSTGRES_DB: postgres
+#          POSTGRES_USER: postgres
+#          POSTGRES_PASSWORD: postgres
+#          POSTGRES_HOST: localhost
+#          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
+#
+#      - name: Run tests with coverage
+#        working-directory: django-test #INPUT
+#        run: poetry run pytest --cov-config=.coveragerc --cov-report=xml --cov=. --durations=5
 #        env:
 #          CI: true
 #          SQL_ENGINE: django.db.backends.postgresql
