enable migration check

diff --git a/.github/workflows/test-workflow-django.yml b/.github/workflows/test-workflow-django.yml
--- a/.github/workflows/test-workflow-django.yml
+++ b/.github/workflows/test-workflow-django.yml
@@ -73,25 +73,25 @@ jobs:
           poetry config http-basic.repowered ${{ secrets.PRIVATE_PYPI_USER }} ${{ secrets.PRIVATE_PYPI_PASSWORD}}
           poetry install --no-interaction --no-root --no-ansi
 
-#      - name: Check Django Migrations
-#        working-directory: django-test #INPUT
-#        if: true #INPUT
-#        run: |
-#          MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
-#          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
-#            echo "<h2>:no_entry_sign: Migration check failed </h2>
-#                    <h3>The message:</h3>
-#                    <br/> $MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
-#            exit 1
-#          fi
-#        env:
-#          CI: true
-#          ENGINE: django.db.backends.postgresql #INPUT/SECRETS/VARS
-#          POSTGRES_DB: postgres
-#          POSTGRES_USER: postgres
-#          POSTGRES_PASSWORD: postgres
-#          POSTGRES_HOST: localhost
-#          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
+      - name: Check Django Migrations
+        working-directory: django-test #INPUT
+        if: true #INPUT
+        run: |
+          MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
+          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
+            echo "<h2>:no_entry_sign: Migration check failed </h2>
+                    <h3>The message:</h3>
+                    <br/> $MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+        env:
+          CI: true
+          ENGINE: django.db.backends.postgresql #INPUT/SECRETS/VARS
+          POSTGRES_DB: postgres
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
+          POSTGRES_HOST: localhost
+          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
 #
 #      - name: Run tests with coverage
 #        working-directory: django-test #INPUT
