echo failures

diff --git a/.github/workflows/test-workflow-django.yml b/.github/workflows/test-workflow-django.yml
--- a/.github/workflows/test-workflow-django.yml
+++ b/.github/workflows/test-workflow-django.yml
@@ -119,18 +119,18 @@ jobs:
             2>&1 | tee /dev/stderr >test_report.md
           HAS_FAILURES=$(cat test_report.md | { grep 'failed' || true; } 2>&1 )
           echo "$HAS_FAILURES"
-#          if [ -f test_report.md ]; then
-#              if [ "$HAS_FAILURES" == '' ]; then
-#                echo "<h1>:white_check_mark: Tests Succeeded</h1>" >> $GITHUB_STEP_SUMMARY
-#              else
-#                echo "<details><summary>:x: Tests Failed</summary>" >> $GITHUB_STEP_SUMMARY
-#                echo "" >> $GITHUB_STEP_SUMMARY
-#                cat test_report.md >> $GITHUB_STEP_SUMMARY
-#                echo "" >> $GITHUB_STEP_SUMMARY
-#                echo "</details>" >> $GITHUB_STEP_SUMMARY
-#                exit 3
-#              fi
-#          fi
+          if [ -f test_report.md ]; then
+              if [ "$HAS_FAILURES" == '' ]; then
+                echo "<h1>:white_check_mark: Tests Succeeded</h1>" >> $GITHUB_STEP_SUMMARY
+              else
+                echo "<details><summary>:x: Tests Failed</summary>" >> $GITHUB_STEP_SUMMARY
+                echo "" >> $GITHUB_STEP_SUMMARY
+                cat test_report.md >> $GITHUB_STEP_SUMMARY
+                echo "" >> $GITHUB_STEP_SUMMARY
+                echo "</details>" >> $GITHUB_STEP_SUMMARY
+                exit 3
+              fi
+          fi
         env:
           CI: true
           COLUMNS: 100
