with all test options

diff --git a/.github/workflows/test-workflow-django.yml b/.github/workflows/test-workflow-django.yml
--- a/.github/workflows/test-workflow-django.yml
+++ b/.github/workflows/test-workflow-django.yml
@@ -79,12 +79,28 @@ jobs:
           poetry config --list
           poetry install --no-interaction --no-root --no-ansi
 
-      - name: Simple tests
+#      - name: Download tetstmondata artifact
+#        continue-on-error: true
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: django-test/.testmondata
+
+      - name: Run tests with coverage (+2 parallel procs, MD report on failures, testmon(-noselect) on branch, 5 slowest tests)
         working-directory: django-test #INPUT
+        # Bash commands explanations:
+        #  2>&1: redirect stderr to stdout
+        #  tee /dev/stderr >test_report: Copy standard input to 'test_report' and to stdout
+        #  { grep 'failed' || true; }: makes sure that grep does not exit with code 1 when no failures are found
+        # If branch dev/main/hotfix then --testmon-noselect else --testmon
         run: |
-          poetry run pytest -v --md-report --md-report-flavor gfm --md-report-exclude-outcomes passed skipped xpassed --md-report-output test_report.md
+          poetry run pytest -v \
+            --md-report --md-report-flavor gfm --md-report-exclude-outcomes passed skipped xpassed --md-report-tee test_report.md \
+            --testmon --durations=5 --numprocesses=2 \
+            --cov-config=.coveragerc --cov-report=xml --cov=.
         env:
           CI: true
+          COLUMNS: 100
+          REPORT_OUTPUT: test_report.md
           SQL_DATABASE: ${{ vars.POSTGRES_DB }}
           SQL_USER: ${{ vars.POSTGRES_USER }}
           SQL_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
@@ -96,80 +112,12 @@ jobs:
         if: failure()
         run: |
           if [ -f test_report.md ]; then
-            echo "<details><summary>:x: Tests Failed</summary>" >> $GITHUB_STEP_SUMMARY
+            echo "<summary>:x: Tests Failed</summary>" >> $GITHUB_STEP_SUMMARY
             echo "" >> $GITHUB_STEP_SUMMARY
             cat test_report.md >> $GITHUB_STEP_SUMMARY
-            echo "" >> $GITHUB_STEP_SUMMARY
-            echo "</details>" >> $GITHUB_STEP_SUMMARY
           else
-            echo "Tests failed but not report file was generated"
+            echo "Tests failed but report file 'test_report.md' was not generated"
           fi
-
-#      - name: Download tetstmondata artifact
-#        continue-on-error: true
-#        uses: actions/download-artifact@v4
-#        with:
-#          name: django-test/.testmondata
-
-#      - name: Check Django Migrations
-#        working-directory: django-test #INPUT
-#        run: |
-#          MIGRATION_MSG=$(poetry run python manage.py makemigrations --dry-run 2>&1 )
-#          if [[ "$MIGRATION_MSG" != 'No changes detected' ]]; then
-#            echo "<h2>:no_entry_sign: Migration check failed </h2>" >> $GITHUB_STEP_SUMMARY
-#            echo "<h3>The message:</h3>" >> $GITHUB_STEP_SUMMARY
-#            echo "$MIGRATION_MSG" >> $GITHUB_STEP_SUMMARY
-#            exit 3
-#          fi
-#        env:
-#          CI: true
-#          SQL_DATABASE: ${{ vars.POSTGRES_DB }}
-#          SQL_USER: ${{ vars.POSTGRES_USER }}
-#          SQL_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
-#          SQL_HOST: ${{ vars.POSTGRES_HOST }}
-#          SQL_PORT: 5432
-
-      - name: Run tests with coverage
-        working-directory: django-test #INPUT
-        # Bash commands explanations:
-        # 2>&1: redirect stderr to stdout
-        # tee /dev/stderr >test_report: Copy standard input to 'test_report' and to stdout
-        # { grep 'failed' || true; }: makes sure that grep does not exit with code 1 when no failures are found
-
-        #if branch dev/main/hotfix then --testmon-noselect else --testmon
-        run: |
-          poetry run pytest -v \
-            --md-report --md-report-flavor gfm --md-report-exclude-outcomes passed skipped xpassed --md-report-tee "$REPORT_OUTPUT" \
-            --testmon --durations=5 --numprocesses=2 \
-            --cov-config=.coveragerc --cov-report=xml --cov=. 
-          echo "------------------"
-          echo ""
-          cat test_report.md
-          echo ""
-          echo "------------------"
-          HAS_FAILURES=$(cat test_report.md | { grep 'failed' || true; } 2>&1 )
-          echo "$HAS_FAILURES"
-          if [ -f test_report.md ]; then
-              if [ "$HAS_FAILURES" == '' ]; then
-                echo "<h1>:white_check_mark: Tests Succeeded</h1>" >> $GITHUB_STEP_SUMMARY
-              else
-                echo "<details><summary>:x: Tests Failed</summary>" >> $GITHUB_STEP_SUMMARY
-                echo "" >> $GITHUB_STEP_SUMMARY
-                cat test_report.md >> $GITHUB_STEP_SUMMARY
-                echo "" >> $GITHUB_STEP_SUMMARY
-                echo "</details>" >> $GITHUB_STEP_SUMMARY
-                exit 3
-              fi
-          fi
-        env:
-          CI: true
-          COLUMNS: 100
-          REPORT_OUTPUT: test_report.md
-          SQL_DATABASE: ${{ vars.POSTGRES_DB }}
-          SQL_USER: ${{ vars.POSTGRES_USER }}
-          SQL_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
-          SQL_HOST: ${{ vars.POSTGRES_HOST }}
-#          SQL_PORT: 5432
 
 #      - name: Archive test coverage report
 #        uses: actions/upload-artifact@v4
